### PR TITLE
Fix compilation with recent ocaml trunk

### PR DESCRIPTION
**Pull request by toots**
I have the following failure on a recent debian sid:
```
/home/toots/.opam/4.03.0+trunk/bin/ocamlc.opt -c -cc "cc" -ccopt "-fPIC -g -O2 -DFFTW3F_EXISTS -DHASH_EXISTS \
			-DPIC   \
			    -o fftw3_stubs.o " fftw3_stubs.c
In file included from fftw3_stubs.c:44:0:
bigarray_stubs.c: In function ‘caml_ba_compare’:
bigarray_stubs.c:139:27: error: unknown type name ‘int32’
     DO_INTEGER_COMPARISON(int32);
                           ^
bigarray_stubs.c:98:5: note: in definition of macro ‘DO_INTEGER_COMPARISON’
   { type * p1 = b1->data; type * p2 = b2->data; \
     ^
bigarray_stubs.c:139:27: error: unknown type name ‘int32’
     DO_INTEGER_COMPARISON(int32);
                           ^
bigarray_stubs.c:98:27: note: in definition of macro ‘DO_INTEGER_COMPARISON’
   { type * p1 = b1->data; type * p2 = b2->data; \
                           ^
bigarray_stubs.c:139:27: error: unknown type name ‘int32’
     DO_INTEGER_COMPARISON(int32);
                           ^
bigarray_stubs.c:100:7: note: in definition of macro ‘DO_INTEGER_COMPARISON’
       type e1 = *p1++; type e2 = *p2++; \
       ^
bigarray_stubs.c:139:27: error: unknown type name ‘int32’
     DO_INTEGER_COMPARISON(int32);
                           ^
bigarray_stubs.c:100:24: note: in definition of macro ‘DO_INTEGER_COMPARISON’
       type e1 = *p1++; type e2 = *p2++; \
                        ^
bigarray_stubs.c:142:27: error: unknown type name ‘int64’
     DO_INTEGER_COMPARISON(int64);
                           ^
bigarray_stubs.c:98:5: note: in definition of macro ‘DO_INTEGER_COMPARISON’
   { type * p1 = b1->data; type * p2 = b2->data; \
     ^
bigarray_stubs.c:142:27: error: unknown type name ‘int64’
     DO_INTEGER_COMPARISON(int64);
                           ^
bigarray_stubs.c:98:27: note: in definition of macro ‘DO_INTEGER_COMPARISON’
   { type * p1 = b1->data; type * p2 = b2->data; \
                           ^
bigarray_stubs.c:142:27: error: unknown type name ‘int64’
     DO_INTEGER_COMPARISON(int64);
                           ^
bigarray_stubs.c:100:7: note: in definition of macro ‘DO_INTEGER_COMPARISON’
       type e1 = *p1++; type e2 = *p2++; \
       ^
bigarray_stubs.c:142:27: error: unknown type name ‘int64’
     DO_INTEGER_COMPARISON(int64);
                           ^
bigarray_stubs.c:100:24: note: in definition of macro ‘DO_INTEGER_COMPARISON’
       type e1 = *p1++; type e2 = *p2++; \
                        ^
In file included from fftw3_stubs.c:44:0:
bigarray_stubs.c: In function ‘caml_ba_hash’:
bigarray_stubs.c:175:3: error: unknown type name ‘uint32’
   uint32 h, w;
   ^
bigarray_stubs.c:214:5: error: unknown type name ‘uint32’
     uint32 * p = b->data;
     ^
bigarray_stubs.c:229:5: error: unknown type name ‘int64’
     int64 * p = b->data;
     ^
bigarray_stubs.c: In function ‘caml_ba_serialize_longarray’:
bigarray_stubs.c:346:29: error: ‘int32’ undeclared (first use in this function)
       caml_serialize_int_4((int32) *p);
                             ^
bigarray_stubs.c:346:29: note: each undeclared identifier is reported only once for each function it appears in
../OCamlMakefile:1124: recipe for target 'fftw3_stubs.o' failed
```

It's fixed with this PR. I suspect it comes from the C compiler not having the same set of predefined types as before.

### CODE REVIEW

**Comment by Chris00** [comment]
You see it does not pass the Travis test.  Please give more information about your setting (ocaml version,...).

**Comment by Chris00** [comment]
I tried with *4.03.0+trunk* and it compiles fine on my machine.

**Comment by toots** [comment]
I'm using `4.03.0+trunk` as well, from `opam`. I think the commit that you want to look at is here: https://github.com/ocaml/ocaml/commit/b868c05ec91a7ee193010a421de768a3b1a80952

**Comment by Chris00** [comment]
I took this as an opportunity to upgrade to the latest bigarray code (commit 7b721d1).  Please confirm that it works for you — I'll them make a new release.

**Comment by Chris00** [comment]
I enriched the Travis CI with various compilers and it compiles fine.

**Pull request closed without merging**
